services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
  worker:
    image: lab2/worker:latest
  aggregator:
    image: lab2/aggregator:latest
  producer:
    image: lab2/aggregator:latest
